// @ts-check
// This file is automatically generated by a `metapak`
// module. Do not change it elsewhere, changes would
// be overridden.

import eslint from '@eslint/js';
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginJest from 'eslint-plugin-jest';

export default defineConfig(
  {
    files: ['**/*.ts'],
    ignores: ['**/*.d.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.strict,
      tseslint.configs.stylistic,
    ],
    rules: {
      '@typescript-eslint/consistent-type-definitions': 'warn'
    }
  },
  {
    files: ['*.test.ts'],
    ...eslintPluginJest.configs['flat/recommended'],
  },
  eslintConfigPrettier,
  {
    name: 'Project config',
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaVersion: 'latest',
        tsconfigRootDir: import.meta.dirname,
      }
    },
    ignores: ['*.d.ts'],
  },
);
